version: '3.7'

services:
    dev_server:
        container_name: morph_analyzer_production_server
        build:
            context: .
            target: production
        command: bash -c "npm run build && npm run start"
        environment: 
            NODE_ENV: production
        volumes: # allows changes to be made in this directory to be applied to container
            - .:/usr/src/server
        ports:
            - "8080:8080"