version: '3.7'

services:
    dev_server:
        container_name: morph_analyzer_development_server
        build:
            context: .
            target: development
        command: npm run dev
        environment: 
            NODE_ENV: development
        volumes: # allows changes to be made in this directory to be applied to container
            - .:/usr/src/server
        ports:
            - "8080:8080"