version: '3.7'

services:
    dev_server:
        container_name: morph_analyzer_test_server
        build:
            context: .
            target: development
        command: npm run test
        volumes: # allows coverage and test data to be written 
            - .:/usr/src/server